### ISSUE TITLE
this is beautiful

### ISSUE THREAD

**Issue by htor** [maximecb/Turing-Drawings#3]
there are no issues whatsoever, just wanted to say thank you for making this nice piece of software! 
it really generates some fantastic images/sequences!!

**Comment by maximecb** [comment]
Thanks for the positive feedback htor :)

It is one of the little weekend projects I'm the most proud of.

**Comment by htor** [comment]
you're welcome. this made me want to spend a weekend myself with turing machines and a canvas, actually. any idea if performance will get bad if you put this to work on a full-screen canvas? i'm into audio visualizations and live coding, so i'm thinking that using this module for that would be great too..

**Comment by maximecb** [comment]
It was quite fast back in 2012. I imagine JS engines have gotten slightly faster since. You can also use some tricks like (x + y) | 0 to coerce values to integers, give performance hints to the JS engine, use typed arrays, etc.

Besides that, it's going to depend on the resolution, but one thing that's interesting about Turing Drawings is that the read/write head is moving all over, changing one pixel at a time. So technically, you can render this at any frame rate you want, by adjusting the number of updates you allow for each frame.

You could also try to make a version that runs in a shader program on the GPU with WebGL, and uses multiple read/write heads, though that comes with its own difficulties.

**Comment by htor** [comment]
thanks, i'll try and experiment with this in mind!
